spring:
  datasource:
    #    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sandbox?rewriteBatchedStatements=true&useUnicode=true&characterEncoding=UTF8&connectTimeout=5000&socketTimeout=120000&serverTimezone=Asia/Seoul
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
  r2dbc:
    url: r2dbc:pool:mysql://localhost:3306/sandbox
    username: root
    password: root
  batch:
    jdbc:
      initialize-schema: always
logging:
  level:
    org.springframework.r2dbc.core: debug